# Generated by Django 5.0 on 2023-12-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('startup', 'Стартап'), ('investor', 'Инвестор'), ('support_organization', 'Организация поддержки')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Подана'), ('under_review', 'Рассматривается'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('additional_info_required', 'Ожидает дополнительной информации'), ('completed', 'Завершена')], default='pending', max_length=50)),
                ('details', models.TextField()),
            ],
        ),
    ]
